### PR TITLE
Use osmosis PbfReader instead of BlockInputStream

### PR DESCRIPTION
**Pull request by guillaumerose**
I tried the osmosis-pbf2 jar and the result are quite impressive. In fact, it allows us to use all our cpus.

Running the readme example code on ile-de-france-latest.osm.pbf (Paris region), I had pretty good results on my machine (4 cores).

Before (in seconds) : 29.132, 28.475, 28.417, 28.170
After :  22.619, 20.790, 20.673, 20.544

Tell me what do you think about that. 

I think it's a great move. The code is much better, there is no more magic : OsmonautBinaryParser is gone. I just needed to write an adapter between osmosis pojos and ours.

### CODE REVIEW

**Comment by laurentg** [comment]
Looks great. Do you know if the performance improvement is due to multi-threading only, or the `osmosis-pbf2` code is also better?

**Comment by guillaumerose** [comment]
I cant say but all my cpu work now. Maybe we should introduce a parameter for defining how many cpu do we want to use. 

During profiling yesterday, I've seen that reader lost a large amount of time creating unused objects. Maybe we can patch this and filter what we want. 
During relations scanning, we dont care about unpacking ways and nodes.

https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/impl/PbfBlobDecoder.java#L415

**Comment by MorbZ** [comment]
The performance gain is impressive. Nice work.

One issue I see here is that every entity object is created twice. First the Osmosis version and then converted. I created the OsmonautBinaryParser to avoid exactly that in the earlier version.

In osmosis-pbf2 the [PbfBlobDecoder](https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/impl/PbfBlobDecoder.java) does what OsmonautBinaryParser was doing. The problem here is that the PbfBlobDecoder is hardcoded in the [PbfDecoder](https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/impl/PbfDecoder.java) which is hardcoded in the [PbfReader](https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/PbfReader.java). That means we would have to replace these three files in order to use our own PbfBlobDecoder.

I think a better solution here would be to copy all the files from org.openstreetmap.osmosis.pbf2.v0_6 and fit them to our needs. Some aren't even needed. This way we could almost completely remove Osmosis as a dependency and just use protobuf. The only files that would be used from Osmosis would be the protobuf definition files as it was before.

Also one thing I noticed about multithreading is the order in which the entities come in. In the final scan the order is crucial as we need all nodes before we get the first way object, and all ways before the first relation. Have you tested the code and can confirm that the order is retaining even with multithreading?

**Comment by guillaumerose** [comment]
Yes I will try to include directly the PbfReader. 
The order is still the same. In fact, the sink is always processed by the main thread.

**Comment by guillaumerose** [comment]
Merging this then I will create a branch with the included PbfReader.

**Pull request merged**
